##
## This file is part of the ubertoothp project.
##
## Copyright (C) 2016 Kage Shen <kgat96@gmail.com>
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 2 as
## published by the Free Software Foundation.
##

#for debug
V = 1

BINARY = main

OBJS = cc.o

LDSCRIPT = ./link.ld

include ../Makefile.include

